services:
  mail_service:
    build: .
    container_name: mail-service
    env_file: ./.env
    restart: unless-stopped
    networks: [backend]
    expose:
      - "5000"

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks: [backend]

networks:
  backend:
    external: true

volumes:
  caddy_data:
  caddy_config:
